server:
  port: ${APPLICATION_PORT:18082}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_URL:192.168.1.65:1521:orcl}
    username: ${ORACLE_USERNAME:CONN}
    password: ${ORACLE_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000
      read-only: false
  application:
    name: conn-ibmmq-service

ibm:
  mq:
    queue-manager: ${IBM_MQ_QMGR:CRCS.QM}
    conn-name: ${IBM_MQ_HOST:192.168.1.66}(${IBM_MQ_PORT:1416})
    channel: SYSTEM.DEF.SVRCONN
    user: mqm
#    user: MUSR_MQADMIN
    password: ${IBM_MQ_MQM_PASSWORD:mqm}
    ccsidDef: 1208

logging.level.com.suncd.conn.ibmmq.dao: info
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

